// T12.L08 — Reading an OTDR Trace
// Working lesson: event table, loss events, reflection events, cursor placement, trace anatomy
// Source: EXFO AN194 | VIAVI OTDR Reference Guide Vol 1 | TIA-455-61

import React from 'react';
import LessonLayout from '../../components/LessonLayout.jsx';
import Quiz from '../../components/primitives/Quiz.jsx';
import Flashcard from '../../components/Flashcard.jsx';

export const meta = {
  id: 'T12.L08',
  course_id: 'T12',
  title: 'Reading an OTDR Trace',
  order: 8,
  lesson_type: 'working',
  prerequisites: ['T12.L03', 'T12.L04', 'T12.L07'],
  learning_objectives: [
    'Identify the six main zones of a standard OTDR trace on a distance-vs-dB plot',
    'Distinguish a loss event (step-down) from a reflection event (spike) on the trace',
    'Describe the OTDR event table and what each column represents',
    'Explain the consequences of placing a measurement cursor inside a dead zone',
  ],
  estimated_minutes: 30,
  vocabulary_introduced: [
    'event table',
    'loss event',
    'reflection event',
    'manual cursor placement',
    'end-of-fiber marker',
  ],
  vocabulary_assumed: [
    { term: 'Rayleigh backscatter', source_lesson_id: 'T12.L03' },
    { term: 'pulse width', source_lesson_id: 'T12.L03' },
    { term: 'EIOR', source_lesson_id: 'T12.L03' },
    { term: 'EDZ', source_lesson_id: 'T12.L04' },
    { term: 'ADZ', source_lesson_id: 'T12.L04' },
    { term: 'launch cable', source_lesson_id: 'T12.L04' },
    { term: 'ghost reflection', source_lesson_id: 'T12.L04' },
    { term: 'bidirectional OTDR', source_lesson_id: 'T12.L07' },
  ],
  key_terms: [
    {
      term: 'event table',
      definition:
        'The tabular summary generated by the OTDR software listing every detected event on the fiber under test. Each row typically shows: event number, distance from OTDR port, event type (reflection, loss, end), loss (dB), reflectance (dB), cumulative loss from port, and pass/fail status vs. a programmed threshold. The event table is the primary deliverable from an OTDR measurement — it becomes part of the acceptance test documentation.',
    },
    {
      term: 'loss event',
      definition:
        'An OTDR event where the backscatter trace steps downward at a specific distance, indicating optical power was consumed at that point. Typical loss events include fusion splices, mechanical splices, and macrobends. A loss event shows a step-down with little to no reflection spike. The loss magnitude is read as the dB difference between the backscatter slope before and after the event.',
    },
    {
      term: 'reflection event',
      definition:
        'An OTDR event where the trace shows a sharp upward spike (reflection) at a specific distance, caused by a discrete Fresnel reflection (connector end-face, air gap, fiber break, cleaved end). A reflection event always coincides with some loss (the reflected energy doesn\'t continue down the fiber). Characterized by both a reflection magnitude (dBm or dB return loss) and a loss value (how much the backscatter slope drops after the spike).',
    },
    {
      term: 'manual cursor placement',
      definition:
        'The process of manually positioning the OTDR measurement cursors on the trace to define the start and end of a backscatter slope segment for LSA (Least-Squares Algorithm) fitting. Required when auto-detection misidentifies event boundaries, when an event falls inside a dead zone, or when two closely spaced events need to be separated. Cursor placement inside a dead zone produces an incorrect loss reading — cursors must always be placed on flat, undisturbed backscatter.',
    },
    {
      term: 'end-of-fiber marker',
      definition:
        'The large reflection spike at the far end of the fiber under test, caused by the Fresnel reflection at the fiber end-face (whether polished, cleaved, or broken). The OTDR uses the end-of-fiber marker to determine the total fiber length. An end-of-fiber marker should appear as a spike followed by the trace dropping into the noise floor. If the trace drops to noise before any end spike, the fiber end is beyond the OTDR\'s dynamic range at the current pulse width.',
    },
  ],
};

export const vocabulary_introduced = meta.vocabulary_introduced;
export const key_terms = meta.key_terms;

export default function T12L08_ReadingOTDRTrace() {
  return (
    <LessonLayout meta={meta}>

      {/* ── FOUNDATIONS ── */}
      <section data-tier="foundations">
        <h2>What You're Actually Looking At on an OTDR Screen</h2>

        <p>
          The OTDR display shows a graph with <strong>distance</strong> on the horizontal axis
          (meters or kilometers) and <strong>optical power level</strong> on the vertical axis
          (in dB, referenced to the backscatter level at the OTDR port). The graph is sometimes
          called the "trace" or "signature" of the fiber.
        </p>
        <p>
          Think of it like this: the OTDR is listening to an echo. It fires a pulse of light down
          the fiber and plots how much echo it receives back over time. Time translates directly to
          distance (using the IOR). Strong echo = high on the graph. Weak echo = low on the graph.
        </p>
        <p>
          A perfect fiber — no splices, no connectors, no bends, just fiber — would look like a
          straight diagonal line gradually sloping downward from left to right. The slope represents
          attenuation: the further the light travels, the weaker the backscatter signal that returns.
          In reality, every splice, connector, macrobend, and end-face creates a visible deviation from
          that straight slope.
        </p>

        <AnnotatedDiagram
          imageUrl="/diagrams/T12/otdr-trace-anatomy.svg"
          alt="Full OTDR trace showing launch ramp, backscatter slope, splice step-downs, connector reflection spikes, and end-of-fiber"
          annotations={[
            { x: 8, y: 30, label: 'Launch ramp', description: 'Initial saturated region where the OTDR port connector reflection overwhelms the detector. Distance = 0 to the launch cable length.' },
            { x: 20, y: 50, label: 'First in-line connector', description: 'Reflection spike (Fresnel) + small loss step-down. This connector is visible because the launch cable pushed it beyond the dead zone.' },
            { x: 35, y: 65, label: 'Backscatter slope', description: 'The straight downward-sloping region between events. Slope = fiber attenuation in dB/km. Steeper = higher attenuation.' },
            { x: 55, y: 72, label: 'Splice (loss event)', description: 'A step-down with no spike. Loss magnitude = vertical drop. Typical fusion splice: 0.02–0.10 dB.' },
            { x: 75, y: 82, label: 'End-of-fiber marker', description: 'Large reflection spike at the far-end connector or cleaved end-face. Trace drops to noise floor after this point.' },
          ]}
        />

        <h3>The six zones of a standard OSP OTDR trace</h3>
        <ol>
          <li><strong>Launch ramp:</strong> the dead zone at the start. Corresponds to the OTDR port's own reflection. Extends to the end of the launch cable.</li>
          <li><strong>Launch cable backscatter:</strong> the clean straight slope of the launch reel. Used to verify the reel is in good condition.</li>
          <li><strong>First link connector:</strong> visible as a reflection + loss step. This is what the launch cable is there to reveal.</li>
          <li><strong>Span backscatter + events:</strong> the main section. Each splice = a step-down. Each connector or break = a spike + step-down.</li>
          <li><strong>End-of-fiber marker:</strong> the far-end connector or cleaved end-face.</li>
          <li><strong>Noise floor:</strong> below the end marker, no useful information. If this appears before the end marker, the fiber span is beyond the OTDR's dynamic range.</li>
        </ol>

        <p className="text-slate-400 text-sm mb-3 mt-6 p-3 border-l-4 border-slate-500">
          <strong>Callback:</strong> Recall from <strong>T12.L04 Dead Zones</strong> — the launch cable length is set based on the ADZ (attenuation dead zone), which is why you can see the first connector's true loss. That's the entire reason launch cables exist.
        </p>
      </section>

      {/* ── WORKING ── */}
      <section data-tier="working">
        <h2>The Event Table — Reading the OTDR's Summary</h2>

        <p>
          Modern OTDRs auto-detect events and produce an <strong>event table</strong>: a row-by-row
          list of every detected event on the fiber. You'll submit this table as part of the splice
          acceptance documentation. Knowing how to read it is essential.
        </p>

        <table>
          <thead>
            <tr>
              <th>#</th>
              <th>Distance (km)</th>
              <th>Type</th>
              <th>Loss (dB)</th>
              <th>Reflectance (dB)</th>
              <th>Cumulative loss (dB)</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            <tr><td>1</td><td>0.000</td><td>Launch</td><td>—</td><td>−18.5</td><td>0.00</td><td>—</td></tr>
            <tr><td>2</td><td>1.014</td><td>Connector</td><td>0.22</td><td>−42.1</td><td>0.56</td><td>Pass</td></tr>
            <tr><td>3</td><td>4.287</td><td>Splice</td><td>0.07</td><td>&gt;−65</td><td>1.60</td><td>Pass</td></tr>
            <tr><td>4</td><td>8.551</td><td>Splice</td><td>0.04</td><td>&gt;−65</td><td>2.60</td><td>Pass</td></tr>
            <tr><td>5</td><td>12.000</td><td>End</td><td>—</td><td>−20.3</td><td>3.22</td><td>—</td></tr>
          </tbody>
        </table>

        <p>Key columns to understand:</p>
        <ul>
          <li>
            <strong>Type:</strong> Launch (OTDR port), Connector (reflection + loss), Splice
            (loss only, low reflectance), End (far-end).
          </li>
          <li>
            <strong>Loss (dB):</strong> Loss attributed to this specific event (not cumulative).
            For bidirectional tests, this column should show the averaged value.
          </li>
          <li>
            <strong>Reflectance (dB):</strong> How much light bounced back at this event. Fusion
            splices should be &gt;−65 dB (essentially non-reflective). A value above −35 dB at a
            splice indicates a problem (air gap, contamination, or poor fusion).
          </li>
          <li>
            <strong>Cumulative loss:</strong> Total loss from the OTDR port to this point, including
            fiber attenuation + all events. Useful for end-to-end loss budget verification.
          </li>
          <li>
            <strong>Status:</strong> Pass/fail vs. the acceptance threshold programmed into the OTDR.
            Not a substitute for human review — the OTDR doesn't know which threshold applies to
            your contract.
          </li>
        </ul>

        <h3>Loss event vs. reflection event — visual identification</h3>
        <p>
          On the trace display:
        </p>
        <ul>
          <li>
            <strong>Loss event (splice, macrobend):</strong> trace steps down suddenly with
            <em>no spike</em>. The step-down is the loss. After the step, backscatter continues
            at a slightly lower level. Good fusion splices look like very small step-downs
            (0.02–0.10 dB) — often barely visible to the eye.
          </li>
          <li>
            <strong>Reflection event (connector, break):</strong> trace spikes sharply upward
            then drops below the pre-event backscatter level. The spike indicates energy being
            reflected back. The drop below the prior level is the transmission loss. The
            combination of spike + drop is the classic connector signature.
          </li>
        </ul>

        <h3>Manual cursor placement — and why the dead zone matters</h3>
        <p>
          The OTDR's auto-detection algorithm places cursors on the trace to define where to
          run the backscatter slope fit (LSA). Occasionally the algorithm places cursors wrong —
          especially on noisy traces, closely-spaced events, or events near the dead zone.
        </p>
        <p>
          <strong>Rule: never leave a cursor inside a dead zone or on a non-flat portion of
          the trace.</strong> If a cursor sits inside the ADZ of a reflection, the slope fit
          will be skewed by the ring-down curve, and the calculated loss will be wrong. Move the
          cursor to flat backscatter on both sides of the event.
        </p>
        <p>
          How to identify a cursor placement problem:
        </p>
        <ul>
          <li>The calculated loss seems implausibly high or shows a gainer on a splice you expect to be normal.</li>
          <li>The trace region where the cursor sits shows a curve rather than a straight slope.</li>
          <li>The cursor distance is less than the ADZ away from a prior reflective event.</li>
        </ul>
        <p>
          Move both cursors to flat, clean backscatter on each side of the event, re-run the
          slope fit, and the loss reading will be accurate.
        </p>
      </section>

      {/* ── ADVANCED ── */}
      <section data-tier="advanced">
      <h2>Advanced: LSA Fit Quality and Confidence Region</h2>
        <p>
          The OTDR uses a Least-Squares Algorithm (LSA) to fit a straight line to the backscatter
          data points in the region between your two cursors. The fit quality is affected by:
          (1) number of data points in the cursor region (more points = better fit),
          (2) noise level (higher signal = lower noise = better fit), and
          (3) the flatness of the backscatter in the cursor region.
        </p>
        <p>
          Higher-end OTDRs display a confidence interval or R² value for the LSA fit. A poor
          R² (below ~0.95) indicates the trace in the cursor region is not well-modeled by a
          straight line — typically because the cursor is too close to an event boundary, there's
          a mode partition noise effect, or the averaging time was too short. Extending the averaging
          time (see L03) improves the fit quality by reducing trace noise.
        </p>
        <p>
          For OTDR-driven splice reports submitted to RUS or NECA/FOA 301 specs, the trace file
          (in Bellcore SOR format) captures the cursor positions, LSA windows, and event table.
          Reviewers can verify cursor placement was correct by replaying the SOR file in any
          compatible viewer.
        </p>
      </section>

      {/* ── QUIZ ── */}
      <section data-tier="quiz">
        <Quiz
          id="T12L08-quiz"
          questions={[
            {
              id: 'q1',
              type: 'multiple-choice',
              text: 'On an OTDR trace, a sharp upward spike appears at 5.2 km, followed by a downward step in the backscatter level. What type of event is this?',
              options: [
                { id: 'a', text: 'A loss event — fusion splice with very high loss' },
                { id: 'b', text: 'A reflection event — connector or end-face with both reflectance and transmission loss' },
                { id: 'c', text: 'A ghost reflection — spurious peak caused by multiple bounces' },
                { id: 'd', text: 'An ADZ artifact — caused by cursor placement inside a dead zone' },
              ],
              correct: 'b',
              explanation: 'A spike followed by a downward step is the characteristic signature of a reflection event: a connector, air gap, or end-face creates a Fresnel reflection (spike) and also has transmission loss (the step-down in backscatter level). A fusion splice loss event shows only a step-down with no spike. Ghost reflections show a spike with NO loss step.',
            },
            {
              id: 'q2',
              type: 'multiple-choice',
              text: 'The OTDR auto-detection places a measurement cursor 2 m after a strong connector reflection event. The ADZ at this pulse width is 8 m. What will happen to the loss reading?',
              options: [
                { id: 'a', text: 'The reading will be perfectly accurate — the cursor is after the event' },
                { id: 'b', text: 'The reading will be inaccurate — the cursor is inside the ADZ where the trace is still settling from the reflection ring-down' },
                { id: 'c', text: 'The reading will be too high — inside the ADZ, all events read worse than they actually are' },
                { id: 'd', text: 'The reading will show a false gainer — inside the ADZ, the trace artificially slopes upward' },
              ],
              correct: 'b',
              explanation: 'A cursor placed 2 m after a reflection event, when the ADZ is 8 m, means the cursor is inside the ADZ. The backscatter trace in the ADZ still reflects the ring-down from the reflection, not a flat slope. The LSA fit on non-flat data produces an inaccurate loss reading. Move the cursor to beyond 8 m from the event to get a valid measurement.',
            },
            {
              id: 'q3',
              type: 'multiple-choice',
              text: 'In the OTDR event table, a fusion splice shows a reflectance value of −28 dB. What does this indicate?',
              options: [
                { id: 'a', text: 'Normal — all fusion splices have reflectance values in the −25 to −30 dB range' },
                { id: 'b', text: 'A potential problem — fusion splices should be essentially non-reflective (> −55 dB); −28 dB suggests an air gap, contamination, or failed fusion' },
                { id: 'c', text: 'The splice is a connector — fusion splices are never reported in the reflectance column' },
                { id: 'd', text: 'Normal for APC connectors, which typically show −28 dB reflectance' },
              ],
              correct: 'b',
              explanation: 'A properly executed fusion splice produces no detectable reflection — typically > −65 dB (essentially zero reflectance for field instruments). A −28 dB reading at a splice location indicates a significant Fresnel reflection, which only occurs when there is an air gap between the fiber ends, end-face contamination, or a failed (non-fused) splice that is simply pressing the two ends together. This splice must be re-done.',
            },
          ]}
        />
      </section>

      {/* ── FLASHCARDS ── */}
      <section data-tier="flashcards">
        <h2>Key Terms</h2>
        {meta.key_terms.map((kt) => (
          <Flashcard key={kt.term} term={kt.term} definition={kt.definition} />
        ))}
      </section>


      <section className="mt-8 p-5 border-l-4 border-blue-500 bg-slate-800/40 rounded">
        <h3 className="text-blue-300 text-lg font-semibold mb-3">Tying It Together</h3>
        <p className="text-slate-200 mb-3">
          This lesson builds on:
        </p>
        <ul className="space-y-2 text-slate-300 text-sm list-disc ml-5">
    <li><strong>T12.L03</strong> — Part of the broader OSP workflow.</li>
    <li><strong>T12.L03</strong> — Part of the broader OSP workflow.</li>
    <li><strong>T12.L03</strong> — Part of the broader OSP workflow.</li>
        </ul>
        <p className="text-slate-200 mt-3 text-sm italic">
          Each step in the OSP process feeds into the next — understanding these connections strengthens your grasp of the whole system.
        </p>
      </section>
    </LessonLayout>
  );
}
