// Net-new — T19.L05
// T19.L05 — HVAC and Fire Suppression — Awareness
// Foundation lesson: CRAC units, cooling load, clean-agent fire suppression, pre-action sprinkler

import React from 'react';
import LessonLayout from '../../components/LessonLayout.jsx';
import Quiz from '../../components/primitives/Quiz.jsx';
import SideBySide from '../../components/primitives/SideBySide.jsx';
import { Flashcard } from '../../components/Flashcard.jsx';

export const meta = {
  id: 'T19.L05',
  course_id: 'T19',
  title: 'HVAC and Fire Suppression — Awareness',
  order: 5,
  lesson_type: 'foundation',
  prerequisites: ['T19.L04'],
  vocabulary_introduced: [
    'CRAC',
    'sensible heat',
    'clean-agent suppression',
    'pre-action sprinkler',
    'ASHRAE thermal envelope',
    'heat load',
  ],
  key_terms: [
    {
      term: 'CRAC',
      definition: 'Computer Room Air Conditioner — a precision cooling unit designed specifically for equipment rooms. Unlike a residential air conditioner that removes both sensible heat (temperature) and latent heat (humidity), a CRAC is designed primarily to remove sensible heat while maintaining tight humidity control. CRAC units are floor-mounted, draw air from under a raised floor or from the front, and discharge cold air into the equipment aisles. Standard in large COs. Rural huts commonly use mini-split units instead.',
    },
    {
      term: 'sensible heat',
      definition: 'Heat that causes a temperature change when added to or removed from a material — the heat you can "sense" with a thermometer. In a CO equipment room, sensible heat is the heat generated by equipment (OLTs, rectifiers, HVAC fans, lighting). Sensible heat is measured in BTU/hr or kilowatts. For every 1 kW of electrical power consumed by equipment in a CO, approximately 3,412 BTU/hr of sensible heat must be removed by the cooling system.',
    },
    {
      term: 'clean-agent suppression',
      definition: 'A fire suppression system that uses a gaseous chemical agent (not water) to suppress fires in equipment rooms without damaging electronics. Common agents: Novec 1230 (3M), FM-200 (Chemours), Inergen (inert gas blend). The agent is discharged rapidly into the protected space, suppressing the fire by reducing oxygen concentration (inert gases) or interrupting the combustion chain reaction (chemical agents). Equipment remains functional after discharge — no water, no mess. Required by NFPA 75/76 [confirm edition — NFPA 75: IT equipment fire protection; NFPA 76: telecommunications facility fire protection] for server rooms and CO equipment spaces where water suppression would destroy equipment.',
    },
    {
      term: 'pre-action sprinkler',
      definition: 'A sprinkler system in which water is held back from the supply piping by a pre-action valve. The valve opens only when BOTH (a) a fire detection device activates AND (b) a sprinkler head fuses from heat. This two-step requirement prevents accidental water discharge from a single mechanical failure. Pre-action sprinklers are used in CO equipment rooms where a wet-pipe sprinkler (water always in the pipes) would risk leakage damage to electronics. Pre-action is less expensive than clean-agent suppression but still delivers water to electronics in a fire.',
    },
    {
      term: 'ASHRAE thermal envelope',
      definition: 'The temperature and humidity range recommended by ASHRAE (American Society of Heating, Refrigerating and Air-Conditioning Engineers) for safe operation of IT and telecom equipment. ASHRAE Standard 55 (human comfort) and ASHRAE TC 9.9 (IT equipment) define these ranges. For Class A2 equipment: 64.4°F–80.6°F (18°C–27°C) at 20–80% relative humidity. Equipment operating outside this envelope experiences accelerated aging, thermal throttling, or failure.',
    },
    {
      term: 'heat load',
      definition: 'The total rate of heat generation inside a CO equipment room from all sources — active equipment (OLT, rectifiers, HVAC fans), lighting, and heat conduction through walls. Measured in BTU/hr or kilowatts. The HVAC system must remove the heat load continuously to maintain temperature within the ASHRAE thermal envelope. For an OSP engineer sizing a hut HVAC: heat load (kW) = electrical power consumed by all equipment (kW) × 1.0 (all electrical energy eventually becomes heat).',
    },
  ],
  vocabulary_assumed: [
    { term: 'CO', source_lesson_id: 'T19.L01' },
    { term: 'hut', source_lesson_id: 'T19.L01' },
    { term: 'equipment room', source_lesson_id: 'T19.L01' },
    { term: 'OLT', source_lesson_id: 'T19.L02' },
    { term: 'power plant', source_lesson_id: 'T19.L03' },
  ],
  estimated_minutes: 15,
};

export default function T19L05_HvacAndFireSuppressionAwareness() {
  return (
    <LessonLayout meta={meta}>

      {/* ── FOUNDATIONS ─────────────────────────────────────────────────── */}
      <section data-tier="foundations">
        <h2>In Plain English</h2>
        <p>
          Every watt of electrical power consumed by equipment in a CO eventually becomes
          heat. An OLT drawing 2,000 watts of DC power generates 2,000 watts of heat — that's
          about 6,824 BTU/hr, enough to heat a small room. Now add the rectifiers, the lighting,
          the HVAC fans themselves, and heat conducted through the building walls on a hot summer
          day. Without active cooling, the temperature inside a sealed equipment hut will reach
          equipment-damaging levels within 45–90 minutes.
        </p>
        <p className="mt-2">
          The OSP engineer's job: specify HVAC capacity that can remove the heat load
          continuously, with at least N+1 redundancy so one unit failure doesn't kill the site.
          For fire suppression, understand the difference between systems that destroy electronics
          (wet-pipe sprinkler) and systems that don't (clean-agent), and spec accordingly.
        </p>

        <h3 className="mt-4 font-semibold">Acronyms in this lesson</h3>
        <table className="w-full text-sm border border-white/10 rounded-lg mt-2">
          <thead className="bg-white/5 text-slate-200">
            <tr>
              <th className="px-3 py-2 text-left">Acronym</th>
              <th className="px-3 py-2 text-left">Full name</th>
              <th className="px-3 py-2 text-left">What it means in practice</th>
            </tr>
          </thead>
          <tbody className="text-slate-300/90">
            <tr className="border-t border-white/10">
              <td className="px-3 py-2 font-mono">CRAC</td>
              <td className="px-3 py-2">Computer Room Air Conditioner</td>
              <td className="px-3 py-2">Precision cooling unit for equipment rooms; controls temperature and humidity precisely</td>
            </tr>
            <tr className="border-t border-white/10">
              <td className="px-3 py-2 font-mono">ASHRAE</td>
              <td className="px-3 py-2">American Society of Heating, Refrigerating and Air-Conditioning Engineers</td>
              <td className="px-3 py-2">The organization that publishes recommended temperature and humidity ranges for IT equipment</td>
            </tr>
            <tr className="border-t border-white/10">
              <td className="px-3 py-2 font-mono">BTU/hr</td>
              <td className="px-3 py-2">British Thermal Units per hour</td>
              <td className="px-3 py-2">Unit of heat transfer rate; 1 kW = 3,412 BTU/hr</td>
            </tr>
            <tr className="border-t border-white/10">
              <td className="px-3 py-2 font-mono">NFPA 75 / 76</td>
              <td className="px-3 py-2">National Fire Protection Association Standards 75 and 76</td>
              <td className="px-3 py-2">Fire protection standards for IT equipment rooms (75) and telecom facilities (76)</td>
            </tr>
          </tbody>
        </table>

        <h3 className="mt-5 font-semibold">The 1 kW = 3,412 BTU/hr conversion — why it matters</h3>
        <p className="mt-2">
          All electrical energy consumed by equipment eventually becomes heat (the second law of
          thermodynamics — no electrical process is perfectly efficient). So:
        </p>
        <div className="rounded-lg bg-black/30 border border-white/10 p-4 font-mono text-sm my-3 text-slate-200">
          Heat load (BTU/hr) = Total equipment power (kW) × 3,412 BTU/hr per kW
        </div>
        <p className="text-sm text-slate-300/80">
          Example: OLT draws 2 kW + Rectifiers draw 1 kW + Lighting 0.2 kW = 3.2 kW total.
          Heat load = 3.2 × 3,412 = 10,918 BTU/hr ≈ 0.91 tons of cooling. Plus solar gain
          through walls and roof in summer adds to this. Specify 1.5 tons minimum for this
          scenario to have reasonable headroom.
        </p>

        {/* ── FLASHCARDS ───────────────────────────────────────────────── */}
        <Flashcard
          deckId="T19-L05"
          cards={[
            {
              id: 'T19-L05-fc-crac',
              front: 'What is a CRAC unit?',
              back: 'Computer Room Air Conditioner — precision cooling for equipment rooms. Removes sensible heat while maintaining tight humidity control. Floor-mounted, draws air from under raised floor or front face, discharges cold air to equipment aisles. Standard in large COs; rural huts often use mini-split units instead.',
            },
            {
              id: 'T19-L05-fc-sensible-heat',
              front: 'What is sensible heat in a CO context?',
              back: 'Heat that causes a temperature change — measurable with a thermometer. Generated by all electrical equipment in the CO. 1 kW of consumed power = 3,412 BTU/hr of sensible heat that must be removed by the cooling system. All electrical energy eventually becomes heat.',
            },
            {
              id: 'T19-L05-fc-clean-agent',
              front: 'What is a clean-agent fire suppression system?',
              back: 'A fire suppression system using gaseous chemical agent (Novec 1230, FM-200, Inergen) instead of water. Suppresses fire without damaging electronics. Equipment remains functional after discharge. Required by NFPA 75/76 [confirm edition] for equipment rooms where water would destroy electronics.',
            },
            {
              id: 'T19-L05-fc-pre-action',
              front: 'What is a pre-action sprinkler system?',
              back: 'A sprinkler system where water is held back by a pre-action valve. Valve opens only when BOTH a fire detector activates AND a sprinkler head fuses from heat. Two-step requirement prevents accidental water discharge. Used in COs where wet-pipe sprinkler leakage risk is unacceptable. Less expensive than clean-agent but still delivers water to electronics in a fire.',
            },
            {
              id: 'T19-L05-fc-ashrae',
              front: 'What is the ASHRAE thermal envelope for CO equipment?',
              back: 'ASHRAE TC 9.9 Class A2: 64.4°F–80.6°F (18°C–27°C) at 20–80% relative humidity. Equipment outside this range experiences accelerated aging, thermal throttling, or failure. HVAC must maintain this range continuously.',
            },
            {
              id: 'T19-L05-fc-heat-load',
              front: 'How do you calculate heat load for a CO equipment room?',
              back: 'Heat load (BTU/hr) = Total equipment power (kW) × 3,412 BTU/hr per kW. Include OLT, rectifiers, lighting, and fans. Add solar gain through walls/roof. Specify HVAC capacity to exceed this with N+1 redundancy.',
            },
          ]}
        />
      </section>

      {/* ── WORKING ─────────────────────────────────────────────────────── */}
      <section data-tier="working">
        <h2>HVAC Selection and Fire Suppression — What to Specify</h2>

        {/* SIDE BY SIDE: CRAC vs Mini-Split */}
        <SideBySide
          title="CRAC Unit vs. Mini-Split — Which Cooling System for Which Building?"
          leftLabel="CRAC Unit (Full CO)"
          rightLabel="Mini-Split (Rural Hut)"
          rows={[
            {
              label: 'Typical cooling capacity',
              left: '5–30 tons (60,000–360,000 BTU/hr) per unit',
              right: '1–3 tons (12,000–36,000 BTU/hr)',
            },
            {
              label: 'Airflow design',
              left: 'Draws warm air from raised-floor plenum or hot aisle; discharges cold air to equipment inlet (cold aisle). Designed for high-density rack cooling.',
              right: 'Standard split-system: outdoor compressor + indoor air handler. Sufficient for small huts with 1–3 equipment racks.',
            },
            {
              label: 'Humidity control',
              left: 'Precision humidity control (±5% RH) to prevent static discharge and condensation on equipment.',
              right: 'Basic residential humidity management — not precision. Adequate for rural huts if equipment is rated for commercial humidity range.',
            },
            {
              label: 'Redundancy on RUS-program builds',
              left: 'N+1 or N+2 CRAC units — one unit failure does not degrade cooling.',
              right: 'OSP spec should require N+1 mini-split units (two independent units, each capable of full load). One compressor failure in summer without redundancy = OLT thermal shutdown within 90 minutes.',
            },
            {
              label: 'Monitoring',
              left: 'BMS (Building Management System) integration — alarms to NOC for temperature exceedance, humidity, filter status, compressor fault.',
              right: 'Minimum: remote temperature sensor with high-temp alarm to NOC (30°C setpoint). A $50 cellular-connected sensor prevents a multi-hour undetected outage.',
            },
          ]}
        />

        <h3 className="mt-5 font-semibold">Fire suppression — the three-option decision</h3>
        <div className="mt-3 overflow-x-auto">
          <table className="w-full text-sm border border-white/10 rounded-lg">
            <thead className="bg-white/5 text-slate-200">
              <tr>
                <th className="px-3 py-2 text-left">System type</th>
                <th className="px-3 py-2 text-left">How it works</th>
                <th className="px-3 py-2 text-left">Equipment damage on activation</th>
                <th className="px-3 py-2 text-left">When to specify</th>
              </tr>
            </thead>
            <tbody className="text-slate-300/90">
              <tr className="border-t border-white/10">
                <td className="px-3 py-2 font-semibold">Clean agent<br/>(Novec 1230, FM-200)</td>
                <td className="px-3 py-2">Gaseous agent discharged into sealed room. Suppresses fire in 10 seconds by oxygen displacement (inert gas) or chain reaction interruption (chemical). Room must seal for 10-minute hold time.</td>
                <td className="px-3 py-2 text-green-400">Minimal — equipment operational after discharge. Clean-up: none.</td>
                <td className="px-3 py-2">Large CO or any facility where equipment replacement cost far exceeds suppression system cost. Required by NFPA 75/76 for full CO equipment rooms. [confirm edition]</td>
              </tr>
              <tr className="border-t border-white/10">
                <td className="px-3 py-2 font-semibold">Pre-action sprinkler</td>
                <td className="px-3 py-2">Water held back by pre-action valve; needs fire detector + fusible head to release. Reduces accidental discharge vs. wet-pipe.</td>
                <td className="px-3 py-2 text-yellow-400">Significant — water destroys electronics. Equipment replacement required. Facility downtime: days to weeks.</td>
                <td className="px-3 py-2">Mid-size COs where clean-agent cost is prohibitive but wet-pipe risk is unacceptable. Not preferred for active equipment bays.</td>
              </tr>
              <tr className="border-t border-white/10">
                <td className="px-3 py-2 font-semibold">None (rural huts)</td>
                <td className="px-3 py-2">No suppression system. Relies on early smoke detection and fire department response.</td>
                <td className="px-3 py-2 text-red-400">Total loss if fire progresses beyond incipient stage. Facility replacement required.</td>
                <td className="px-3 py-2">Very small rural huts where local fire department response is acceptable risk. Requires smoke/heat detection with NOC alarm at minimum.</td>
              </tr>
            </tbody>
          </table>
        </div>

        <div className="mt-4 p-4 border border-amber-400/30 bg-amber-400/5 rounded-lg text-sm">
          <p className="font-semibold text-amber-300 mb-1">Book vs. Field — Rural Hut HVAC Redundancy</p>
          <p className="text-slate-300/90">
            <strong>Book (ASHRAE TC 9.9 / BICSI 002-2024 [confirm edition]):</strong> Minimum N+1
            cooling redundancy for any production telecom facility. Each unit capable of
            handling full load independently.
          </p>
          <p className="text-slate-300/90 mt-2">
            <strong>Field:</strong> The majority of rural FTTH huts deployed in the last decade
            have a single mini-split unit. No redundancy. When the compressor fails in July in
            Georgia — where outdoor temperatures hit 95°F — the hut interior reaches 50°C+ within
            2 hours. OLT thermal protection kicks in and shuts the unit down. The fix costs
            $3,000–5,000 for an emergency HVAC service call plus equipment downtime. The N+1
            redundant unit at original installation time costs $2,500. This is one of the clearest
            examples of false economy in rural hut design. Specify N+1 at build time.
          </p>
          <p className="text-slate-300/90 mt-2">
            <strong>Arid climate note:</strong> In arid or high-altitude climates (Colorado, New Mexico,
            West Texas) where relative humidity can drop below 20% RH, the ASHRAE lower humidity limit
            becomes the active constraint — at &lt;20% RH, static electricity buildup on electronic
            equipment creates electrostatic discharge (ESD) risk. Purpose-built CRAC units include
            humidification capability; standard mini-split units do not. Where arid conditions are expected,
            specify either a CRAC unit with humidification or a separate in-room humidifier with a
            humidity controller — and include the humidity spec in the hut commissioning checklist.
          </p>
        </div>
      </section>

      {/* ── PER-LESSON QUIZ ──────────────────────────────────────────────── */}
      <Quiz
        title="T19.L05 Check — HVAC and Fire Suppression Awareness"
        mode="multiple-choice"
        questions={[
          {
            id: 'T19-L05-Q1',
            type: 'mc',
            prompt:
              'An OLT shelf draws 2.4 kW of DC power. Rectifiers draw 0.8 kW. Lighting draws 0.3 kW. What is the approximate heat load in BTU/hr that the HVAC must remove?',
            choices: [
              '3,500 BTU/hr',
              '11,920 BTU/hr',
              '34,120 BTU/hr',
              '8,500 BTU/hr',
            ],
            answerIndex: 1,
            explanation:
              'Total power = 2.4 + 0.8 + 0.3 = 3.5 kW. Heat load = 3.5 kW × 3,412 BTU/hr per kW = 11,942 BTU/hr ≈ 11,920 BTU/hr. Plus solar gain through walls — add 15–20% for an insulated building in a hot climate. Specify a 1.5-ton mini-split (18,000 BTU/hr) at minimum for this scenario, or two 1-ton units for N+1 redundancy.',
          },
          {
            id: 'T19-L05-Q2',
            type: 'mc',
            prompt:
              'A fire breaks out in a CO equipment room protected by a clean-agent suppression system (Novec 1230). The system activates. After the fire is suppressed and the room ventilated, what happens to the OLT equipment?',
            choices: [
              'The OLT equipment is destroyed — gaseous agents are as damaging as water to electronics',
              'The OLT equipment is typically operational — clean agents suppress fire without residue, liquid, or electrical damage. Normal commissioning checks verify no heat or smoke damage.',
              'The OLT must be replaced immediately as a precaution — insurance requirements mandate it after any suppression event',
              'The gaseous agent bonds to connector surfaces, requiring lens cleaning of all fiber connectors',
            ],
            answerIndex: 1,
            explanation:
              'Clean-agent suppression systems (Novec 1230, FM-200, Inergen) are designed specifically to suppress fires in electronic environments without equipment damage. They leave no residue, cause no electrical shorts, and do not degrade connectors. After discharge, the room is ventilated, equipment is inspected for smoke or heat damage, and if none is found, operations resume. This is the primary advantage over water-based suppression in CO environments.',
            citation: 'NFPA 75 [confirm edition]; NFPA 76 [confirm edition].',
          },
          {
            id: 'T19-L05-Q3',
            type: 'fill-in-blank',
            prompt:
              'The ASHRAE Class A2 recommended upper temperature limit for IT and telecom equipment inlet is ____ °C (approximately 80.6°F).',
            answer: '27',
            answerDisplay: '27°C',
            explanation:
              'ASHRAE TC 9.9 Class A2 upper dry-bulb temperature limit is 27°C (80.6°F) at the equipment inlet. This is the temperature at the front face of the equipment rack, measured at air entry — not ambient room temperature. Equipment operating above this temperature enters accelerated aging territory and may trigger thermal throttling or automatic shutdown.',
          },
          {
            id: 'T19-L05-Q4',
            type: 'mc',
            prompt:
              'A pre-action sprinkler system activates (both conditions: fire detector triggers AND sprinkler head fuses). What is the primary concern for the CO equipment?',
            choices: [
              'No concern — pre-action systems use clean agent, not water',
              'Water discharge. Pre-action delays water release compared to wet-pipe, but when both conditions are met, water does discharge from the sprinkler heads. Electronics in the fire zone will be damaged.',
              'Overpressure — the system pressurizes the room to suppress the fire without water or agent',
              'CO2 discharge — pre-action systems use CO2 rather than water or clean agent',
            ],
            answerIndex: 1,
            explanation:
              'Pre-action sprinkler systems still deliver water when both conditions are met (detector activation + head fusion). The two-condition requirement reduces false discharges (which destroy electronics without a fire) compared to wet-pipe systems. But when a real fire occurs, water does discharge. Electronics in the affected zone will be damaged. Pre-action is a middle ground — better than wet-pipe for reducing false discharges, but not as equipment-safe as clean-agent.',
          },
        ]}
      />

    </LessonLayout>
  );
}
